title: eliza's test page
author: eliza roach
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a page for me to practice coding. Nothing to see here, folks...

# social links
github_username:  elizanroach

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
